server:
  port: 7073

spring:
  profiles:
    active: hadoop
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:33066/compass?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  redis:
    host: localhost
    port: 6379
    password: "root"
    database: 0
  elasticsearch:
    nodes: localhost:19527
    username:
    password:
    log-prefix: "compass-log-summary-"
    detector-prefix: "compass-detector-app-"
    gc-prefix: "compass-gc-log-"
    job-prefix: "compass-job-analysis-"
    task-app-prefix: "compass-task-app-"

  kafka:
    consumer:
      auto-offset-reset: "latest"
      max-poll-interval-ms: 300000
      security-protocol: ""
      sasl-mechanism: ""
      sasl-jaas-config: ""

custom:
  redisConsumer:
    enable: true
    maxThreadPoolSize: 10
    logRecordList: "{lua}:log:record"
    processingHash: "{lua}:parser:processing"
    scheduled:
      cron: "0/2 * * * * ?"
      limitTime: 2 # 单位小时
      limitCount: 2 # 次数
  jvmType:
    - Java HotSpot
    - OpenJDK
  # spark event log检测参数
  # disable 默认false;true禁用该检测项
  detector:
    sparkEnvironmentConfig:
      jvmInformation:
        - Java Version
      sparkProperties:
        - spark.driver.memoryOverhead
        - spark.driver.memory
        - spark.executor.memoryOverhead
        - spark.executor.memory
        - spark.executor.cores
        - spark.dynamicAllocation.maxExecutors
        - spark.default.parallelism
        - spark.sql.shuffle.partitions
      systemProperties:
        - sun.java.command
    mapReduceEnvironmentConfig:
      jvmInformation:
        - Java Version
      mapReduceProperties:
        - yarn.app.mapreduce.am.resource.mb
        - mapreduce.reduce.memory.mb
        - mapreduce.map.memory.mb
      systemProperties:
        - sun.java.command
    # 推测任务执行过多（app执行时间超过5分钟，且stage数量超过20）
    speculativeTaskConfig:
      disable: false
      threshold: 20
      # app duration(ms)
      duration: 300000
    # 内存浪费（app执行时间超过5分钟，且内存浪费超过70%）
    memWasteConfig:
      disable: false
      threshold: 70
      # app duration(ms)
      duration: 300000
    # 内存浪费（app执行时间超过5分钟，且cpu浪费超过50%）
    cpuWasteConfig:
      disable: false
      # app duration(ms)
      duration: 300000
      driverThreshold: 50
      executorThreshold: 50
    # 作业耗时异常（job执行时间超过5分钟，（jobTime-stageTime）/jobTime > 30% ）
    jobDurationConfig:
      disable: false
      threshold: 30
      # job duration(ms)
      duration: 300000
    # stage耗时异常（stage执行时间超过5分钟，（stageTime-taskTime）/stageTime > 30% ）
    stageDurationConfig:
      disable: false
      threshold: 30
      # stage duration(ms)
      duration: 300000
    # task长尾（app执行时间超过5分钟，且 最大执行时间/50分位中位数 > 10% ）
    taskDurationConfig:
      disable: false
      threshold: 10
      # app duration(ms)
      duration: 300000
      taskDurationThreshold: 300000
    # hdfs卡顿（task执行时间超过5分钟，且hdfs文件读取速率小于10M/s）
    hdfsStuckConfig:
      disable: false
      threshold: 10
      # MB
      taskSize: 10
      # task duration(ms)
      duration: 300000
    # 全局排序异常（task执行时间超过20分钟，taskCount为1，扫描record大于5000W行）
    globalSortConfig:
      disable: false
      taskCount: 1
      records: 1000000
      # task duration
      duration: 1200000
    # 大表扫描异常（app执行时间超过20分钟，扫描record大于50E行）
    largeTableScanConfig:
      disable: false
      scanTable: 50000000
      # app duration(ms)
      duration: 1200000
    # OMM预警（app执行时间超过20分钟，广播行数大于500W行，广播数据的内存大于Driver/executor内存的40%）
    oomWarnConfig:
      disable: false
      oom: 40
      # app duration(ms)
      duration: 1200000
      broadcastRows: 5000000
      broadcastRowsOom: 30
    # 数据倾斜配置（app执行时间超过20分钟，
    # 最大执行时间>执行时间的50分位中位数 * 执行时间的50分位中位数对应的阈值，
    # stage耗时/任务总耗时 < 20%
    dataSkewConfig:
      disable: false
      # app duration(ms)
      duration: 1200000
      # stage耗时/任务总耗时
      stageDurationPercentage: 20
      interval:
        # 0w-5w
        - start: 0
          end: 50000
          threshold: 0
        # 5w-10w
        - start: 50000
          end: 100000
          threshold: 100
        # 10w-100w
        - start: 100000
          end: 1000000
          threshold: 50
        # 100w-500w
        - start: 1000000
          end: 5000000
          threshold: 10
        # 500w-2000w
        - start: 5000000
          end: 20000000
          threshold: 5
        # 2000w-3000w
        - start: 20000000
          end: 30000000
          threshold: 3.5
        # 3000w-4000w
        - start: 30000000
          end: 40000000
          threshold: 3
        # 4000w-5000w
        - start: 40000000
          end: 50000000
          threshold: 2.25
        # 5000w
        - start: 50000000
          end: 0
          threshold: 2
    speculativeMapReduceConfig:
      disable: false
      # app duration(ms)
      duration: 1200000
      mapThreshold: 0
      reduceThreshold: 0